In [24]:
! pip install pandas
! pip install openpyxl
! pip install tabulate
! pip install xlsxwriter

Requirement already satisfied: pandas in c:\users\surenthiran\onedrive\desktop\cardekho\env\lib\site-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\surenthiran\onedrive\desktop\cardekho\env\lib\site-packages (from pandas) (2.1.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\surenthiran\onedrive\desktop\cardekho\env\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\surenthiran\onedrive\desktop\cardekho\env\lib\site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\surenthiran\onedrive\desktop\cardekho\env\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: six>=1.5 in c:\users\surenthiran\onedrive\desktop\cardekho\env\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: openpyxl in c:\users\surenthiran\onedrive\desktop\cardekho\env\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\surenthiran\onedrive\desktop\cardekho\env\lib\site-packages (from openpyxl) (1.1.0)

[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: tabulate in c:\users\surenthiran\onedrive\desktop\cardekho\env\lib\site-packages (0.9.0)

[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: xlsxwriter in c:\users\surenthiran\onedrive\desktop\cardekho\env\lib\site-packages (3.2.0)

[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip

# **Chennai_cars**

In [25]:
import pandas as pd

# Read the Excel file
df = pd.read_excel('C:/Users/Surenthiran/OneDrive/Desktop/CarDekho/chennai_cars.xlsx')

# Display the DataFrame
df

,new_car_detail,new_car_overview,new_car_feature,new_car_specs,car_links
0,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1,"{'it': 0, 'ft': 'Petrol', 'bt': 'Minivans', 'k...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Low...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...
2,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
3,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...
4,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
...,...,...,...,...,...
1414,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1415,"{'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1416,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1417,"{'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1418,"{'it': 0, 'ft': 'Diesel', 'bt': 'Sedan', 'km':...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...

In [26]:
import pandas as pd
from io import BytesIO
import ast

# Replace this with the actual path of your Excel file
excel_file_path = "C:/Users/Surenthiran/OneDrive/Desktop/CarDekho/chennai_cars.xlsx"

# Load the Excel file
df = pd.read_excel(excel_file_path, sheet_name=None)

# Extract the relevant sheet
car_data = df['chennai_cars.csv']

# Convert the 'new_car_detail' column from string representation of dict to actual dict
car_data['new_car_detail'] = car_data['new_car_detail'].apply(eval)

# Create a new DataFrame to hold structured data
structured_data = pd.json_normalize(car_data['new_car_detail'])


# Convert the 'new_car_overview' column from string representation of dict to actual dict
car_data['new_car_overview'] = car_data['new_car_overview'].apply(eval)

# Extract relevant fields from the 'new_car_overview'
extracted_data = []
for overview in car_data['new_car_overview']:
    # Assuming 'overview' contains a dictionary with a 'top' key containing a list of dicts with 'key' and 'value'
    details = {item['key']: item['value'] for item in overview['top']}
    extracted_data.append(details)

# Create a new DataFrame from the extracted data
overview_df = pd.DataFrame(extracted_data)

df = pd.read_excel(excel_file_path, sheet_name=0)

# Extract the 'new_car_specs' column
specs_data = df['new_car_specs']

# Initialize a list to hold the extracted values
extracted_rows = []

# Process each entry in the specs data
for entry in specs_data:
    # Convert string representation of dictionary to actual dictionary
    specs_dict = ast.literal_eval(entry)
    
    # Initialize a dictionary to hold the row data
    row_data = {}
    
    # Extract relevant values from the nested structure
    for spec in specs_dict.get('data', []):
        for item in spec.get('list', []):
            if item['key'] in ['Length', 'Width', 'Height', 'Wheel Base', 'Gear Box', 'Top Speed', 'Alloy Wheel Size','Mileage']:
                row_data[item['key']] = item['value']
    
    # Append the row data to the list
    extracted_rows.append(row_data)

# Create a new DataFrame with the extracted data
extracted_data = pd.DataFrame(extracted_rows)

# Initialize a list to hold extracted mileage values
mileage_data = []

# Loop through the 'new_car_specs' column to extract mileage
for entry in df['new_car_specs']:
    # Convert string representation of dictionary to actual dictionary
    specs_dict = ast.literal_eval(entry)
    
    # Initialize a variable to store the mileage for this car
    mileage = None
    
    # Search for mileage data within the 'top' section of the specs
    for item in specs_dict.get('top', []):
        if item.get('key') == 'Mileage':
            mileage = item.get('value')
            break
    
    # Append the extracted mileage data to the list
    mileage_data.append(mileage)

# Create a new DataFrame to store the mileage data
mileage_df = pd.DataFrame({'Mileage': mileage_data})

# Define the features to extract
features_to_extract = [
    "Power Steering", "Power Windows Front", "Air Conditioner", "Heater",
    "Adjustable Head Lights", "Fog Lights Front", "Anti Lock Braking System",
    "Brake Assist", "Radio", "Low Fuel Warning Light", "Accessory Power Outlet",
    "Digital Odometer", "Manually Adjustable Exterior Rear View Mirror",
    "Child Safety Locks"
]

# Create a new DataFrame for the extracted features
extracted_features_df = pd.DataFrame(features_to_extract, columns=["Feature"])

# Convert the 'new_car_specs' column from string representation of dict to actual dict
car_data['new_car_specs'] = car_data['new_car_specs'].apply(eval)

# Extract the specifications and their values
specifications = []
for specs in car_data['new_car_specs']:
    spec_dict = {item['key']: item['value'] for item in specs['data'][0]['list']}
    specifications.append(spec_dict)

# Create a new DataFrame from the specifications
specs_df = pd.DataFrame(specifications)

# Extract car links
car_links = car_data['car_links'].tolist()

# Create a new DataFrame for the car links
car_links_df = pd.DataFrame(car_links, columns=["Car Links"])

# Append all the DataFrames column-wise
combined_df = pd.concat([structured_data, overview_df, extracted_features_df, specs_df, car_links_df,extracted_data,mileage_df], axis=1)

# Save the combined DataFrame to a new Excel file
output_file = "df1_chennai_cars_data.xlsx"
combined_df.to_excel(output_file, index=False)


print(f"Data Extracted and saved to {output_file}")

Data Extracted and saved to df1_chennai_cars_data.xlsx

# **bangalore_cars**

In [27]:
import pandas as pd

# Read the Excel file
df = pd.read_excel('C:/Users/Surenthiran/OneDrive/Desktop/CarDekho/bangalore_cars.xlsx')

# Display the DataFrame
df

,new_car_detail,new_car_overview,new_car_feature,new_car_specs,car_links
0,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...
2,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
3,"{'it': 0, 'ft': 'Petrol', 'bt': 'Sedan', 'km':...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...
4,"{'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
...,...,...,...,...,...
1476,"{'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1477,"{'it': 0, 'ft': 'Petrol', 'bt': 'Sedan', 'km':...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1478,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1479,"{'it': 0, 'ft': 'Diesel', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1480,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...

In [28]:
import pandas as pd
from io import BytesIO
import ast

# Replace this with the actual path of your Excel file
excel_file_path = "C:/Users/Surenthiran/OneDrive/Desktop/CarDekho/bangalore_cars.xlsx"

# Load the Excel file
df = pd.read_excel(excel_file_path, sheet_name=None)

# Extract the relevant sheet
car_data = df['bangalore_cars.csv']

# Convert the 'new_car_detail' column from string representation of dict to actual dict
car_data['new_car_detail'] = car_data['new_car_detail'].apply(eval)

# Create a new DataFrame to hold structured data
structured_data = pd.json_normalize(car_data['new_car_detail'])


# Convert the 'new_car_overview' column from string representation of dict to actual dict
car_data['new_car_overview'] = car_data['new_car_overview'].apply(eval)

# Extract relevant fields from the 'new_car_overview'
extracted_data = []
for overview in car_data['new_car_overview']:
    # Assuming 'overview' contains a dictionary with a 'top' key containing a list of dicts with 'key' and 'value'
    details = {item['key']: item['value'] for item in overview['top']}
    extracted_data.append(details)

# Create a new DataFrame from the extracted data
overview_df = pd.DataFrame(extracted_data)

df = pd.read_excel(excel_file_path, sheet_name=0)

# Extract the 'new_car_specs' column
specs_data = df['new_car_specs']

# Initialize a list to hold the extracted values
extracted_rows = []

# Process each entry in the specs data
for entry in specs_data:
    # Convert string representation of dictionary to actual dictionary
    specs_dict = ast.literal_eval(entry)
    
    # Initialize a dictionary to hold the row data
    row_data = {}
    
    # Extract relevant values from the nested structure
    for spec in specs_dict.get('data', []):
        for item in spec.get('list', []):
            if item['key'] in ['Length', 'Width', 'Height', 'Wheel Base', 'Gear Box', 'Top Speed', 'Alloy Wheel Size','Mileage']:
                row_data[item['key']] = item['value']
    
    # Append the row data to the list
    extracted_rows.append(row_data)

# Create a new DataFrame with the extracted data
extracted_data = pd.DataFrame(extracted_rows)

# Initialize a list to hold extracted mileage values
mileage_data = []

# Loop through the 'new_car_specs' column to extract mileage
for entry in df['new_car_specs']:
    # Convert string representation of dictionary to actual dictionary
    specs_dict = ast.literal_eval(entry)
    
    # Initialize a variable to store the mileage for this car
    mileage = None
    
    # Search for mileage data within the 'top' section of the specs
    for item in specs_dict.get('top', []):
        if item.get('key') == 'Mileage':
            mileage = item.get('value')
            break
    
    # Append the extracted mileage data to the list
    mileage_data.append(mileage)

# Create a new DataFrame to store the mileage data
mileage_df = pd.DataFrame({'Mileage': mileage_data})

# Define the features to extract
features_to_extract = [
    "Power Steering", "Power Windows Front", "Air Conditioner", "Heater",
    "Adjustable Head Lights", "Fog Lights Front", "Anti Lock Braking System",
    "Brake Assist", "Radio", "Low Fuel Warning Light", "Accessory Power Outlet",
    "Digital Odometer", "Manually Adjustable Exterior Rear View Mirror",
    "Child Safety Locks"
]

# Create a new DataFrame for the extracted features
extracted_features_df = pd.DataFrame(features_to_extract, columns=["Feature"])

# Convert the 'new_car_specs' column from string representation of dict to actual dict
car_data['new_car_specs'] = car_data['new_car_specs'].apply(eval)

# Extract the specifications and their values
specifications = []
for specs in car_data['new_car_specs']:
    spec_dict = {item['key']: item['value'] for item in specs['data'][0]['list']}
    specifications.append(spec_dict)

# Create a new DataFrame from the specifications
specs_df = pd.DataFrame(specifications)

# Extract car links
car_links = car_data['car_links'].tolist()

# Create a new DataFrame for the car links
car_links_df = pd.DataFrame(car_links, columns=["Car Links"])

# Append all the DataFrames column-wise
combined_df = pd.concat([structured_data, overview_df, extracted_features_df, specs_df, car_links_df,extracted_data,mileage_df], axis=1)

# Save the combined DataFrame to a new Excel file
output_file = "df2_bangalore_cars_data.xlsx"
combined_df.to_excel(output_file, index=False)


print(f"Data Extracted and saved to {output_file}")

Data Extracted and saved to df2_bangalore_cars_data.xlsx

# **delhi_cars**

In [29]:
import pandas as pd

# Read the Excel file
df = pd.read_excel('C:/Users/Surenthiran/OneDrive/Desktop/CarDekho/delhi_cars.xlsx')

# Display the DataFrame
df

,new_car_detail,new_car_overview,new_car_feature,new_car_specs,car_links
0,"{'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...
2,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
3,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...
4,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
...,...,...,...,...,...
1480,"{'it': 0, 'ft': 'Petrol', 'bt': 'Sedan', 'km':...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1481,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1482,"{'it': 0, 'ft': 'Petrol', 'bt': 'Sedan', 'km':...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1483,"{'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1484,"{'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'I...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...

In [30]:
import pandas as pd
from io import BytesIO
import ast

# Replace this with the actual path of your Excel file
excel_file_path = "C:/Users/Surenthiran/OneDrive/Desktop/CarDekho/delhi_cars.xlsx"

# Load the Excel file
df = pd.read_excel(excel_file_path, sheet_name=None)

# Extract the relevant sheet
car_data = df['delhi_cars.csv']

# Convert the 'new_car_detail' column from string representation of dict to actual dict
car_data['new_car_detail'] = car_data['new_car_detail'].apply(eval)

# Create a new DataFrame to hold structured data
structured_data = pd.json_normalize(car_data['new_car_detail'])


# Convert the 'new_car_overview' column from string representation of dict to actual dict
car_data['new_car_overview'] = car_data['new_car_overview'].apply(eval)

# Extract relevant fields from the 'new_car_overview'
extracted_data = []
for overview in car_data['new_car_overview']:
    # Assuming 'overview' contains a dictionary with a 'top' key containing a list of dicts with 'key' and 'value'
    details = {item['key']: item['value'] for item in overview['top']}
    extracted_data.append(details)

# Create a new DataFrame from the extracted data
overview_df = pd.DataFrame(extracted_data)

df = pd.read_excel(excel_file_path, sheet_name=0)

# Extract the 'new_car_specs' column
specs_data = df['new_car_specs']

# Initialize a list to hold the extracted values
extracted_rows = []

# Process each entry in the specs data
for entry in specs_data:
    # Convert string representation of dictionary to actual dictionary
    specs_dict = ast.literal_eval(entry)
    
    # Initialize a dictionary to hold the row data
    row_data = {}
    
    # Extract relevant values from the nested structure
    for spec in specs_dict.get('data', []):
        for item in spec.get('list', []):
            if item['key'] in ['Length', 'Width', 'Height', 'Wheel Base', 'Gear Box', 'Top Speed', 'Alloy Wheel Size','Mileage']:
                row_data[item['key']] = item['value']
    
    # Append the row data to the list
    extracted_rows.append(row_data)

# Create a new DataFrame with the extracted data
extracted_data = pd.DataFrame(extracted_rows)

# Initialize a list to hold extracted mileage values
mileage_data = []

# Loop through the 'new_car_specs' column to extract mileage
for entry in df['new_car_specs']:
    # Convert string representation of dictionary to actual dictionary
    specs_dict = ast.literal_eval(entry)
    
    # Initialize a variable to store the mileage for this car
    mileage = None
    
    # Search for mileage data within the 'top' section of the specs
    for item in specs_dict.get('top', []):
        if item.get('key') == 'Mileage':
            mileage = item.get('value')
            break
    
    # Append the extracted mileage data to the list
    mileage_data.append(mileage)

# Create a new DataFrame to store the mileage data
mileage_df = pd.DataFrame({'Mileage': mileage_data})

# Define the features to extract
features_to_extract = [
    "Power Steering", "Power Windows Front", "Air Conditioner", "Heater",
    "Adjustable Head Lights", "Fog Lights Front", "Anti Lock Braking System",
    "Brake Assist", "Radio", "Low Fuel Warning Light", "Accessory Power Outlet",
    "Digital Odometer", "Manually Adjustable Exterior Rear View Mirror",
    "Child Safety Locks"
]

# Create a new DataFrame for the extracted features
extracted_features_df = pd.DataFrame(features_to_extract, columns=["Feature"])

# Convert the 'new_car_specs' column from string representation of dict to actual dict
car_data['new_car_specs'] = car_data['new_car_specs'].apply(eval)

# Extract the specifications and their values
specifications = []
for specs in car_data['new_car_specs']:
    spec_dict = {item['key']: item['value'] for item in specs['data'][0]['list']}
    specifications.append(spec_dict)

# Create a new DataFrame from the specifications
specs_df = pd.DataFrame(specifications)

# Extract car links
car_links = car_data['car_links'].tolist()

# Create a new DataFrame for the car links
car_links_df = pd.DataFrame(car_links, columns=["Car Links"])

# Append all the DataFrames column-wise
combined_df = pd.concat([structured_data, overview_df, extracted_features_df, specs_df, car_links_df,extracted_data,mileage_df], axis=1)

# Save the combined DataFrame to a new Excel file
output_file = "df3_delhi_cars_data.xlsx"
combined_df.to_excel(output_file, index=False)


print(f"Data Extracted and saved to {output_file}")

Data Extracted and saved to df3_delhi_cars_data.xlsx

# **hyderabad_cars**

In [31]:
import pandas as pd

# Read the Excel file
df = pd.read_excel('C:/Users/Surenthiran/OneDrive/Desktop/CarDekho/hyderabad_cars.xlsx')

# Display the DataFrame
df

,new_car_detail,new_car_overview,new_car_feature,new_car_specs,car_links
0,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...
2,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
3,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...
4,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
...,...,...,...,...,...
1478,"{'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1479,"{'it': 0, 'ft': 'Diesel', 'bt': 'Sedan', 'km':...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1480,"{'it': 0, 'ft': 'Diesel', 'bt': 'Sedan', 'km':...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1481,"{'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1482,"{'it': 0, 'ft': 'Diesel', 'bt': 'MUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...

In [32]:
import pandas as pd
from io import BytesIO
import ast

# Replace this with the actual path of your Excel file
excel_file_path = "C:/Users/Surenthiran/OneDrive/Desktop/CarDekho/hyderabad_cars.xlsx"

# Load the Excel file
df = pd.read_excel(excel_file_path, sheet_name=None)

# Extract the relevant sheet
car_data = df['hyderabad_cars.csv']

# Convert the 'new_car_detail' column from string representation of dict to actual dict
car_data['new_car_detail'] = car_data['new_car_detail'].apply(eval)

# Create a new DataFrame to hold structured data
structured_data = pd.json_normalize(car_data['new_car_detail'])


# Convert the 'new_car_overview' column from string representation of dict to actual dict
car_data['new_car_overview'] = car_data['new_car_overview'].apply(eval)

# Extract relevant fields from the 'new_car_overview'
extracted_data = []
for overview in car_data['new_car_overview']:
    # Assuming 'overview' contains a dictionary with a 'top' key containing a list of dicts with 'key' and 'value'
    details = {item['key']: item['value'] for item in overview['top']}
    extracted_data.append(details)

# Create a new DataFrame from the extracted data
overview_df = pd.DataFrame(extracted_data)

df = pd.read_excel(excel_file_path, sheet_name=0)

# Extract the 'new_car_specs' column
specs_data = df['new_car_specs']

# Initialize a list to hold the extracted values
extracted_rows = []

# Process each entry in the specs data
for entry in specs_data:
    # Convert string representation of dictionary to actual dictionary
    specs_dict = ast.literal_eval(entry)
    
    # Initialize a dictionary to hold the row data
    row_data = {}
    
    # Extract relevant values from the nested structure
    for spec in specs_dict.get('data', []):
        for item in spec.get('list', []):
            if item['key'] in ['Length', 'Width', 'Height', 'Wheel Base', 'Gear Box', 'Top Speed', 'Alloy Wheel Size','Mileage']:
                row_data[item['key']] = item['value']
    
    # Append the row data to the list
    extracted_rows.append(row_data)

# Create a new DataFrame with the extracted data
extracted_data = pd.DataFrame(extracted_rows)

# Initialize a list to hold extracted mileage values
mileage_data = []

# Loop through the 'new_car_specs' column to extract mileage
for entry in df['new_car_specs']:
    # Convert string representation of dictionary to actual dictionary
    specs_dict = ast.literal_eval(entry)
    
    # Initialize a variable to store the mileage for this car
    mileage = None
    
    # Search for mileage data within the 'top' section of the specs
    for item in specs_dict.get('top', []):
        if item.get('key') == 'Mileage':
            mileage = item.get('value')
            break
    
    # Append the extracted mileage data to the list
    mileage_data.append(mileage)

# Create a new DataFrame to store the mileage data
mileage_df = pd.DataFrame({'Mileage': mileage_data})

# Define the features to extract
features_to_extract = [
    "Power Steering", "Power Windows Front", "Air Conditioner", "Heater",
    "Adjustable Head Lights", "Fog Lights Front", "Anti Lock Braking System",
    "Brake Assist", "Radio", "Low Fuel Warning Light", "Accessory Power Outlet",
    "Digital Odometer", "Manually Adjustable Exterior Rear View Mirror",
    "Child Safety Locks"
]

# Create a new DataFrame for the extracted features
extracted_features_df = pd.DataFrame(features_to_extract, columns=["Feature"])

# Convert the 'new_car_specs' column from string representation of dict to actual dict
car_data['new_car_specs'] = car_data['new_car_specs'].apply(eval)

# Extract the specifications and their values
specifications = []
for specs in car_data['new_car_specs']:
    spec_dict = {item['key']: item['value'] for item in specs['data'][0]['list']}
    specifications.append(spec_dict)

# Create a new DataFrame from the specifications
specs_df = pd.DataFrame(specifications)

# Extract car links
car_links = car_data['car_links'].tolist()

# Create a new DataFrame for the car links
car_links_df = pd.DataFrame(car_links, columns=["Car Links"])

# Append all the DataFrames column-wise
combined_df = pd.concat([structured_data, overview_df, extracted_features_df, specs_df, car_links_df,extracted_data,mileage_df], axis=1)

# Save the combined DataFrame to a new Excel file
output_file = "df4_hyderabad_cars_data.xlsx"
combined_df.to_excel(output_file, index=False)


print(f"Data Extracted and saved to {output_file}")

Data Extracted and saved to df4_hyderabad_cars_data.xlsx

# **jaipur_cars**

In [33]:
import pandas as pd

# Read the Excel file
df = pd.read_excel('C:/Users/Surenthiran/OneDrive/Desktop/CarDekho/jaipur_cars.xlsx')

# Display the DataFrame
df

,new_car_detail,new_car_overview,new_car_feature,new_car_specs,car_links
0,"{'it': 0, 'ft': 'Diesel', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...
2,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
3,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...
4,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
...,...,...,...,...,...
1115,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1116,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Low...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1117,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1118,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Low...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1119,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...

In [34]:
import pandas as pd
from io import BytesIO
import ast

# Replace this with the actual path of your Excel file
excel_file_path = "C:/Users/Surenthiran/OneDrive/Desktop/CarDekho/jaipur_cars.xlsx"

# Load the Excel file
df = pd.read_excel(excel_file_path, sheet_name=None)

# Extract the relevant sheet
car_data = df['jaipur_cars.csv']

# Convert the 'new_car_detail' column from string representation of dict to actual dict
car_data['new_car_detail'] = car_data['new_car_detail'].apply(eval)

# Create a new DataFrame to hold structured data
structured_data = pd.json_normalize(car_data['new_car_detail'])


# Convert the 'new_car_overview' column from string representation of dict to actual dict
car_data['new_car_overview'] = car_data['new_car_overview'].apply(eval)

# Extract relevant fields from the 'new_car_overview'
extracted_data = []
for overview in car_data['new_car_overview']:
    # Assuming 'overview' contains a dictionary with a 'top' key containing a list of dicts with 'key' and 'value'
    details = {item['key']: item['value'] for item in overview['top']}
    extracted_data.append(details)

# Create a new DataFrame from the extracted data
overview_df = pd.DataFrame(extracted_data)

df = pd.read_excel(excel_file_path, sheet_name=0)

# Extract the 'new_car_specs' column
specs_data = df['new_car_specs']

# Initialize a list to hold the extracted values
extracted_rows = []

# Process each entry in the specs data
for entry in specs_data:
    # Convert string representation of dictionary to actual dictionary
    specs_dict = ast.literal_eval(entry)
    
    # Initialize a dictionary to hold the row data
    row_data = {}
    
    # Extract relevant values from the nested structure
    for spec in specs_dict.get('data', []):
        for item in spec.get('list', []):
            if item['key'] in ['Length', 'Width', 'Height', 'Wheel Base', 'Gear Box', 'Top Speed', 'Alloy Wheel Size','Mileage']:
                row_data[item['key']] = item['value']
    
    # Append the row data to the list
    extracted_rows.append(row_data)

# Create a new DataFrame with the extracted data
extracted_data = pd.DataFrame(extracted_rows)

# Initialize a list to hold extracted mileage values
mileage_data = []

# Loop through the 'new_car_specs' column to extract mileage
for entry in df['new_car_specs']:
    # Convert string representation of dictionary to actual dictionary
    specs_dict = ast.literal_eval(entry)
    
    # Initialize a variable to store the mileage for this car
    mileage = None
    
    # Search for mileage data within the 'top' section of the specs
    for item in specs_dict.get('top', []):
        if item.get('key') == 'Mileage':
            mileage = item.get('value')
            break
    
    # Append the extracted mileage data to the list
    mileage_data.append(mileage)

# Create a new DataFrame to store the mileage data
mileage_df = pd.DataFrame({'Mileage': mileage_data})

# Define the features to extract
features_to_extract = [
    "Power Steering", "Power Windows Front", "Air Conditioner", "Heater",
    "Adjustable Head Lights", "Fog Lights Front", "Anti Lock Braking System",
    "Brake Assist", "Radio", "Low Fuel Warning Light", "Accessory Power Outlet",
    "Digital Odometer", "Manually Adjustable Exterior Rear View Mirror",
    "Child Safety Locks"
]

# Create a new DataFrame for the extracted features
extracted_features_df = pd.DataFrame(features_to_extract, columns=["Feature"])

# Convert the 'new_car_specs' column from string representation of dict to actual dict
car_data['new_car_specs'] = car_data['new_car_specs'].apply(eval)

# Extract the specifications and their values
specifications = []
for specs in car_data['new_car_specs']:
    spec_dict = {item['key']: item['value'] for item in specs['data'][0]['list']}
    specifications.append(spec_dict)

# Create a new DataFrame from the specifications
specs_df = pd.DataFrame(specifications)

# Extract car links
car_links = car_data['car_links'].tolist()

# Create a new DataFrame for the car links
car_links_df = pd.DataFrame(car_links, columns=["Car Links"])

# Append all the DataFrames column-wise
combined_df = pd.concat([structured_data, overview_df, extracted_features_df, specs_df, car_links_df,extracted_data,mileage_df], axis=1)

# Save the combined DataFrame to a new Excel file
output_file = "df5_jaipur_cars_data.xlsx"
combined_df.to_excel(output_file, index=False)


print(f"Data Extracted and saved to {output_file}")

Data Extracted and saved to df5_jaipur_cars_data.xlsx

# **kolkata_cars**

In [35]:
import pandas as pd

# Read the Excel file
df = pd.read_excel('C:/Users/Surenthiran/OneDrive/Desktop/CarDekho/kolkata_cars.xlsx')

# Display the DataFrame
df

,new_car_detail,new_car_overview,new_car_feature,new_car_specs,car_links
0,"{'it': 0, 'ft': 'Petrol', 'bt': 'Sedan', 'km':...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...
2,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
3,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...
4,"{'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
...,...,...,...,...,...
1376,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1377,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1378,"{'it': 0, 'ft': 'Petrol', 'bt': 'Sedan', 'km':...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1379,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1380,"{'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...

In [36]:
import pandas as pd
from io import BytesIO
import ast

# Replace this with the actual path of your Excel file
excel_file_path = "C:/Users/Surenthiran/OneDrive/Desktop/CarDekho/kolkata_cars.xlsx"

# Load the Excel file
df = pd.read_excel(excel_file_path, sheet_name=None)

# Extract the relevant sheet
car_data = df['kolkata_cars.csv']

# Convert the 'new_car_detail' column from string representation of dict to actual dict
car_data['new_car_detail'] = car_data['new_car_detail'].apply(eval)

# Create a new DataFrame to hold structured data
structured_data = pd.json_normalize(car_data['new_car_detail'])


# Convert the 'new_car_overview' column from string representation of dict to actual dict
car_data['new_car_overview'] = car_data['new_car_overview'].apply(eval)

# Extract relevant fields from the 'new_car_overview'
extracted_data = []
for overview in car_data['new_car_overview']:
    # Assuming 'overview' contains a dictionary with a 'top' key containing a list of dicts with 'key' and 'value'
    details = {item['key']: item['value'] for item in overview['top']}
    extracted_data.append(details)

# Create a new DataFrame from the extracted data
overview_df = pd.DataFrame(extracted_data)

df = pd.read_excel(excel_file_path, sheet_name=0)

# Extract the 'new_car_specs' column
specs_data = df['new_car_specs']

# Initialize a list to hold the extracted values
extracted_rows = []

# Process each entry in the specs data
for entry in specs_data:
    # Convert string representation of dictionary to actual dictionary
    specs_dict = ast.literal_eval(entry)
    
    # Initialize a dictionary to hold the row data
    row_data = {}
    
    # Extract relevant values from the nested structure
    for spec in specs_dict.get('data', []):
        for item in spec.get('list', []):
            if item['key'] in ['Length', 'Width', 'Height', 'Wheel Base', 'Gear Box', 'Top Speed', 'Alloy Wheel Size','Mileage']:
                row_data[item['key']] = item['value']
    
    # Append the row data to the list
    extracted_rows.append(row_data)

# Create a new DataFrame with the extracted data
extracted_data = pd.DataFrame(extracted_rows)

# Initialize a list to hold extracted mileage values
mileage_data = []

# Loop through the 'new_car_specs' column to extract mileage
for entry in df['new_car_specs']:
    # Convert string representation of dictionary to actual dictionary
    specs_dict = ast.literal_eval(entry)
    
    # Initialize a variable to store the mileage for this car
    mileage = None
    
    # Search for mileage data within the 'top' section of the specs
    for item in specs_dict.get('top', []):
        if item.get('key') == 'Mileage':
            mileage = item.get('value')
            break
    
    # Append the extracted mileage data to the list
    mileage_data.append(mileage)

# Create a new DataFrame to store the mileage data
mileage_df = pd.DataFrame({'Mileage': mileage_data})

# Define the features to extract
features_to_extract = [
    "Power Steering", "Power Windows Front", "Air Conditioner", "Heater",
    "Adjustable Head Lights", "Fog Lights Front", "Anti Lock Braking System",
    "Brake Assist", "Radio", "Low Fuel Warning Light", "Accessory Power Outlet",
    "Digital Odometer", "Manually Adjustable Exterior Rear View Mirror",
    "Child Safety Locks"
]

# Create a new DataFrame for the extracted features
extracted_features_df = pd.DataFrame(features_to_extract, columns=["Feature"])

# Convert the 'new_car_specs' column from string representation of dict to actual dict
car_data['new_car_specs'] = car_data['new_car_specs'].apply(eval)

# Extract the specifications and their values
specifications = []
for specs in car_data['new_car_specs']:
    spec_dict = {item['key']: item['value'] for item in specs['data'][0]['list']}
    specifications.append(spec_dict)

# Create a new DataFrame from the specifications
specs_df = pd.DataFrame(specifications)

# Extract car links
car_links = car_data['car_links'].tolist()

# Create a new DataFrame for the car links
car_links_df = pd.DataFrame(car_links, columns=["Car Links"])

# Append all the DataFrames column-wise
combined_df = pd.concat([structured_data, overview_df, extracted_features_df, specs_df, car_links_df,extracted_data,mileage_df], axis=1)

# Save the combined DataFrame to a new Excel file
output_file = "df6_kolkata_cars_data.xlsx"
combined_df.to_excel(output_file, index=False)


print(f"Data Extracted and saved to {output_file}")

Data Extracted and saved to df6_kolkata_cars_data.xlsx

# **Handling Missing Values**

## **chennai_cars**

In [85]:
# Read the Excel file
df = pd.read_excel('C:/Users/Surenthiran/OneDrive/Desktop/CarDekho/df1_chennai_cars_data.xlsx')

# Display the DataFrame
df

,it,ft,bt,km,transmission,ownerNo,owner,oem,model,modelYear,...,BoreX Stroke,Car Links,Length,Width,Height,Wheel Base,Gear Box,Alloy Wheel Size,Top Speed,Mileage
0,0,Petrol,SUV,"20,000",Automatic,1,1st Owner,Kia,Kia Sonet,2022,...,NaN,https://www.cardekho.com/used-car-details/used...,3995mm,1790,1642,2500,7-Speed DCT,16,NaN,NaN
1,0,Petrol,Minivans,"20,687",Manual,1,1st Owner,Maruti,Maruti Eeco,2015,...,NaN,https://www.cardekho.com/buy-used-car-details/...,3675mm,1475mm,1800mm,2350mm,5 Speed,NaN,145 Kmph,15.37 kmpl
2,0,Petrol,SUV,"30,000",Manual,1,1st Owner,Nissan,Nissan Magnite,2021,...,72.2 x 81.3,https://www.cardekho.com/used-car-details/used...,3994mm,1758,1572,2500,5 Speed,16,NaN,20 kmpl
3,0,Petrol,Hatchback,"59,247",Manual,1,1st Owner,Hyundai,Hyundai i10,2015,...,NaN,https://www.cardekho.com/buy-used-car-details/...,3585mm,1595mm,1550mm,2380mm,5 Speed,NaN,165 Kmph,19.81 kmpl
4,0,Petrol,Hatchback,"50,000",Manual,1,1st Owner,Honda,Honda Jazz,2015,...,NaN,https://www.cardekho.com/used-car-details/used...,3955mm,1694mm,1544mm,2530mm,5 Speed,15,172 Kmph,18.7 kmpl
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1414,0,Petrol,Hatchback,"42,891",Automatic,1,1st Owner,Maruti,Maruti Swift,2018,...,NaN,https://www.cardekho.com/used-car-details/used...,3840mm,1735mm,1530mm,2450mm,5,NaN,NaN,22 kmpl
1415,0,Diesel,SUV,"59,100",Manual,1,1st Owner,Renault,Renault Duster,2018,...,NaN,https://www.cardekho.com/used-car-details/used...,4315mm,1822mm,1695mm,2673mm,5 speed,16,156 Kmph,19.87 kmpl
1416,0,Petrol,SUV,"55,913",Automatic,1,1st Owner,Tata,Tata Nexon,2018,...,77x85.8,https://www.cardekho.com/used-car-details/used...,3994mm,1811mm,1607mm,2498mm,6 Speed,16,154.19 kmph,17 kmpl
1417,0,Diesel,SUV,"65,000",Automatic,1,1st Owner,Volkswagen,Volkswagen Tiguan,2017,...,74.5 x 81 mm,https://www.cardekho.com/used-car-details/used...,4486mm,1839mm,1672mm,2677mm,7 Speed,18,NaN,16.65 kmpl
1418,0,Diesel,Sedan,"60,000",Automatic,1,1st Owner,BMW,BMW 3 Series GT,2019,...,NaN,https://www.cardekho.com/used-car-details/used...,4824mm,1828mm,1508mm,2920 mm,8 Speed,18,226 Kmph,21.76 kmpl

In [86]:
# Drop unwanted column
df.drop('it', axis=1, inplace=True)
df.drop('ft', axis=1, inplace=True)
df.drop('km', axis=1, inplace=True)
df.drop('ownerNo', axis=1, inplace=True)
df.drop('owner', axis=1, inplace=True)
df.drop('centralVariantId', axis=1, inplace=True)
df.drop('priceActual', axis=1, inplace=True)
df.drop('priceSaving', axis=1, inplace=True)
df.drop('priceFixedText', axis=1, inplace=True)
df.drop('trendingText.imgUrl', axis=1, inplace=True)
df.drop('trendingText.heading', axis=1, inplace=True)
df.drop('trendingText.desc', axis=1, inplace=True)
df.drop('Displacement', axis=1, inplace=True)
df.drop('Value Configuration', axis=1, inplace=True)
df.drop('Compression Ratio', axis=1, inplace=True)
df.drop('BoreX Stroke', axis=1, inplace=True)
df.drop('Car Links', axis=1, inplace=True)
df.drop('Engine Displacement', axis=1, inplace=True)
df.drop('Values per Cylinder', axis=1, inplace=True)
df.drop('Fuel Suppy System', axis=1, inplace=True)

In [87]:
df.to_excel('C:/Users/Surenthiran/OneDrive/Desktop/CarDekho/df1.xlsx', index=False)

print("Data saved to Excel file successfully.")

Data saved to Excel file successfully.

In [89]:
# Import necessary libraries
import pandas as pd
from io import BytesIO

# Load the Excel file (You would need to replace 'file_path' with your actual file path)
file_path = 'C:/Users/Surenthiran/OneDrive/Desktop/CarDekho/df1.xlsx'
df = pd.read_excel(file_path, engine='openpyxl')

# Function to fill or remove missing values
def fill_missing_values(dataframe):
    for column in dataframe.columns:
        if dataframe[column].dtype in ['int64', 'float64']:  # Numerical columns
            # Use mean for imputation
            dataframe[column].fillna(dataframe[column].mean(), inplace=True)
        elif dataframe[column].dtype == 'object':  # Categorical columns
            # Use mode for imputation or create a new category for missing values
            mode_value = dataframe[column].mode()[0]
            dataframe[column].fillna(mode_value, inplace=True)
    return dataframe

# Handle missing values
df_filled = fill_missing_values(df)


# Save the filled dataframe to a new Excel file
output_file_path = 'df1.xlsx'
df_filled.to_excel(output_file_path, index=False)
print(f"Processed file saved as {output_file_path}")

C:\Users\Surenthiran\AppData\Local\Temp\ipykernel_16312\3445640137.py:18: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataframe[column].fillna(mode_value, inplace=True)
C:\Users\Surenthiran\AppData\Local\Temp\ipykernel_16312\3445640137.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataframe[column].fillna(dataframe[column].mean(), inplace=True)

Processed file saved as df1.xlsx

In [90]:
# Import necessary libraries
import pandas as pd
import re
# Load the second Excel file (You need to replace 'file_path' with the actual path of your file)
file_path = 'C:/Users/Surenthiran/OneDrive/Desktop/CarDekho/df1.xlsx'
df2 = pd.read_excel(file_path, engine='openpyxl')

# Function to standardize data formats
def standardize_formats(dataframe):
    # Remove ' kms' from 'Kms Driven' and convert to integer
    if 'Kms Driven' in dataframe.columns:
        dataframe['Kms Driven'] = dataframe['Kms Driven'].str.replace(' Kms', '').str.replace(',', '').astype(int)
    
   # Remove ' Lakh', ' Crore', and handle thousands from 'price' and convert to Lakhs
    if 'price' in dataframe.columns:
    # Remove currency symbol and units like 'Lakh', 'Crore', and commas
     dataframe['price'] = dataframe['price'].str.replace('â‚¹ ', '').str.replace(' ', '').str.replace(',', '')

# #     # Convert the cleaned price column to float
#     dataframe['price'] = dataframe['price'].astype(float)

    # Lambda function to check and convert price
    dataframe['price'] = dataframe['price'].apply(lambda x: float(x.replace('Crore', '').strip()) * 10000000 
                                              if isinstance(x, str) and 'Crore' in x 
                                              else float(x.replace('Lakh', '').strip()) * 100000 
                                              if isinstance(x, str) and 'Lakh' in x 
                                              else float(x))
    

    # Convert 'Seats' to integer
    if 'Seats' in dataframe.columns:
        dataframe['Seats'] = dataframe['Seats'].str.replace(' Seats', '').astype(int)

    # Convert 'Year of Manufacture' to integer
    if 'Year of Manufacture' in dataframe.columns:
        dataframe['Year of Manufacture'] = dataframe['Year of Manufacture'].astype(int)

    # Convert 'No of Cylinder' to integer
    if 'No of Cylinder' in dataframe.columns:
        dataframe['No of Cylinder'] = dataframe['No of Cylinder'].astype(int)

    return dataframe



# Standardize data formats
df2_standardized = standardize_formats(df2)
print("Data formats standardized successfully.")

# Save the standardized dataframe to a new Excel file
output_file_path = 'df11.xlsx'
df2_standardized.to_excel(output_file_path, index=False)
print(f"Standardized file saved as {output_file_path}")

Data formats standardized successfully.
Standardized file saved as df11.xlsx

In [91]:
import pandas as pd
import os

# File paths
input_path = r"C:/Users/Surenthiran/OneDrive/Desktop/CarDekho/df11.xlsx"
output_path = os.path.join(os.path.dirname(input_path), "df11.xlsx")

# Read the Excel file
df = pd.read_excel(input_path)

# Function to add 'mm' if it's missing
def add_mm(value):
    if isinstance(value, str) and not value.endswith('mm'):
        return value + 'mm'
    elif isinstance(value, (int, float)):
        return f"{value}mm"
    return value

# Apply the function to each column
for col in ['Length', 'Width', 'Height', 'Wheel Base']:
    df[col] = df[col].apply(add_mm)

# Save the updated data
df.to_excel(output_path, index=False)

print(f"Data updated and saved to '{output_path}'")

Data updated and saved to 'C:/Users/Surenthiran/OneDrive/Desktop/CarDekho\df11.xlsx'

In [92]:
import pandas as pd
import re

# Function to extract horsepower (HP) and RPM from 'Max Power' column
def extract_hp_rpm(power_str):
    if isinstance(power_str, str):
        # Extract HP value (e.g., "118.36bhp@6000rpm" -> 118.36)
        hp_match = re.search(r'(\d+\.?\d*)bhp', power_str)
        hp = float(hp_match.group(1)) if hp_match else None

        # Extract RPM value (e.g., "118.36bhp@6000rpm" -> 6000)
        rpm_match = re.search(r'@(\d+)rpm', power_str)
        rpm = int(rpm_match.group(1)) if rpm_match else None

        return hp, rpm
    return None, None

# Function to calculate max torque
def calculate_torque(hp, rpm):
    if hp and rpm:
        return round((5252 * hp) / rpm, 2)  # Torque in lb-ft, rounded to 2 decimal places
    return None

# Load the Excel file
input_file_path = r'C:/Users/Surenthiran/OneDrive/Desktop/CarDekho/df11.xlsx'
df = pd.read_excel(input_file_path)

# Ensure that the 'Max Power' column is read as string
df['Max Power'] = df['Max Power'].astype(str)

# Apply extraction and torque calculation to each row
df['Horsepower'], df['RPM'] = zip(*df['Max Power'].map(extract_hp_rpm))
df['Max Torque (Calculated)'] = df.apply(lambda row: calculate_torque(row['Horsepower'], row['RPM']), axis=1)

# Convert the calculated torque to Nm (from lb-ft to Nm: 1 lb-ft = 1.3558 Nm)
df['Max Torque (Calculated)'] = df['Max Torque (Calculated)'].apply(lambda x: round(x * 1.3558, 2) if x else None)

# Save the updated DataFrame back to the same Excel file
output_file_path = input_file_path  # Save to the same file
with pd.ExcelWriter(output_file_path, engine='openpyxl', mode='a', if_sheet_exists='replace') as writer:
    df.to_excel(writer, index=False, sheet_name='Sheet1')

print(f"Max Torque calculated and saved in {output_file_path}")

Max Torque calculated and saved in C:/Users/Surenthiran/OneDrive/Desktop/CarDekho/df11.xlsx

In [93]:
import pandas as pd

# Load the Excel file
input_file_path = r'C:/Users/Surenthiran/OneDrive/Desktop/CarDekho/df11.xlsx'
df = pd.read_excel(input_file_path)

# Remove the 'Max Power' and 'Max Torque' columns
df.drop(columns=['Max Power', 'Max Torque','RPM','Year of Manufacture'], inplace=True)

# Save the updated DataFrame back to the same Excel file
output_file_path = input_file_path  # Save to the same file
with pd.ExcelWriter(output_file_path, engine='openpyxl', mode='a', if_sheet_exists='replace') as writer:
    df.to_excel(writer, index=False, sheet_name='Sheet1')

print(f"Columns 'Max Power' and 'Max Torque' removed and saved in {output_file_path}")

Columns 'Max Power' and 'Max Torque' removed and saved in C:/Users/Surenthiran/OneDrive/Desktop/CarDekho/df11.xlsx

In [94]:
import pandas as pd

# Load the Excel file
input_file_path = r'C:/Users/Surenthiran/OneDrive/Desktop/CarDekho/df11.xlsx'
df = pd.read_excel(input_file_path)

# Rename specific columns using a dictionary
df.rename(columns={
    'bt': 'Body type',
    'transmission': 'Transmission type',
    'oem': 'Original Equipment Manufacturer',
    'model': 'Car model',
    'modelYear': 'Year of car manufacture',
    'variantName': 'Variant name',
    'price': 'Price of the used car',
    'Kms Driven': 'Kilometers driven',
    'Ownership': 'Ownership details',
    'Horsepower': 'Max power',
    'Max Torque (Calculated)': 'Max Torque'
}, inplace=True)

# Save the updated DataFrame back to the same Excel file
output_file_path = input_file_path  # Save to the same file
with pd.ExcelWriter(output_file_path, engine='openpyxl', mode='a', if_sheet_exists='replace') as writer:
    df.to_excel(writer, index=False, sheet_name='Sheet1')

print(f"Column names updated and saved in {output_file_path}")

Column names updated and saved in C:/Users/Surenthiran/OneDrive/Desktop/CarDekho/df11.xlsx

In [95]:
# Import necessary libraries
import pandas as pd
from io import BytesIO

# Load the Excel file (You would need to replace 'file_path' with your actual file path)
file_path = 'C:/Users/Surenthiran/OneDrive/Desktop/CarDekho/df11.xlsx'
df = pd.read_excel(file_path, engine='openpyxl')

# Function to fill or remove missing values
def fill_missing_values(dataframe):
    for column in dataframe.columns:
        if dataframe[column].dtype in ['int64', 'float64']:  # Numerical columns
            # Use mean for imputation
            dataframe[column].fillna(dataframe[column].mean(), inplace=True)
        elif dataframe[column].dtype == 'object':  # Categorical columns
            # Use mode for imputation or create a new category for missing values
            mode_value = dataframe[column].mode()[0]
            dataframe[column].fillna(mode_value, inplace=True)
    return dataframe

# Handle missing values
df_filled = fill_missing_values(df)


# Save the filled dataframe to a new Excel file
output_file_path = 'df11.xlsx'
df_filled.to_excel(output_file_path, index=False)
print(f"Processed file saved as {output_file_path}")

C:\Users\Surenthiran\AppData\Local\Temp\ipykernel_16312\491412742.py:18: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataframe[column].fillna(mode_value, inplace=True)
C:\Users\Surenthiran\AppData\Local\Temp\ipykernel_16312\491412742.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataframe[column].fillna(dataframe[column].mean(), inplace=True)

Processed file saved as df11.xlsx

In [96]:
# null value
df.isnull().sum()

Body type                          0
Transmission type                  0
Original Equipment Manufacturer    0
Car model                          0
Year of car manufacture            0
Variant name                       0
Price of the used car              0
Registration Year                  0
Insurance Validity                 0
Fuel Type                          0
Seats                              0
Kilometers driven                  0
RTO                                0
Ownership details                  0
Transmission                       0
Feature                            0
Color                              0
Engine Type                        0
No of Cylinder                     0
Turbo Charger                      0
Super Charger                      0
Length                             0
Width                              0
Height                             0
Wheel Base                         0
Gear Box                           0
Alloy Wheel Size                   0
Top Speed                          0
Mileage                            0
Max power                          0
Max Torque                         0
dtype: int64

In [97]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1419 entries, 0 to 1418
Data columns (total 31 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Body type                        1419 non-null   object
 1   Transmission type                1419 non-null   object
 2   Original Equipment Manufacturer  1419 non-null   object
 3   Car model                        1419 non-null   object
 4   Year of car manufacture          1419 non-null   int64
 5   Variant name                     1419 non-null   object
 6   Price of the used car            1419 non-null   float64
 7   Registration Year                1419 non-null   object
 8   Insurance Validity               1419 non-null   object
 9   Fuel Type                        1419 non-null   object
 10  Seats                            1419 non-null   int64
 11  Kilometers driven                1419 non-null   int64
 12  RTO                              1419 non-null   object
 13  Ownership details                1419 non-null   object
 14  Transmission                     1419 non-null   object
 15  Feature                          1419 non-null   object
 16  Color                            1419 non-null   object
 17  Engine Type                      1419 non-null   object
 18  No of Cylinder                   1419 non-null   int64
 19  Turbo Charger                    1419 non-null   object
 20  Super Charger                    1419 non-null   object
 21  Length                           1419 non-null   object
 22  Width                            1419 non-null   object
 23  Height                           1419 non-null   object
 24  Wheel Base                       1419 non-null   object
 25  Gear Box                         1419 non-null   object
 26  Alloy Wheel Size                 1419 non-null   object
 27  Top Speed                        1419 non-null   object
 28  Mileage                          1419 non-null   object
 29  Max power                        1419 non-null   float64
 30  Max Torque                       1419 non-null   float64
dtypes: float64(3), int64(4), object(24)
memory usage: 343.8+ KB

In [98]:
df.shape

(1419, 31)

## **bangalore_cars**

In [99]:
# Read the Excel file
df = pd.read_excel('C:/Users/Surenthiran/OneDrive/Desktop/CarDekho/df2_bangalore_cars_data.xlsx')

# Display the DataFrame
df

,it,ft,bt,km,transmission,ownerNo,owner,oem,model,modelYear,...,No Door Numbers,Car Links,Length,Width,Height,Wheel Base,Gear Box,Top Speed,Alloy Wheel Size.1,Mileage
0,0,Petrol,Hatchback,"1,20,000",Manual,3,3rd Owner,Maruti,Maruti Celerio,2015,...,NaN,https://www.cardekho.com/used-car-details/used...,3715mm,1635mm,1565mm,2425mm,5 Speed,150 Kmph,NaN,23.1 kmpl
1,0,Petrol,SUV,"32,706",Manual,2,2nd Owner,Ford,Ford Ecosport,2018,...,NaN,https://www.cardekho.com/buy-used-car-details/...,3998mm,1765mm,1647mm,2519mm,5 Speed,NaN,16,17 kmpl
2,0,Petrol,Hatchback,"11,949",Manual,1,1st Owner,Tata,Tata Tiago,2018,...,NaN,https://www.cardekho.com/used-car-details/used...,3746mm,1647mm,1535mm,2400mm,5 Speed,150 kmph,14,23.84 kmpl
3,0,Petrol,Sedan,"17,794",Manual,1,1st Owner,Hyundai,Hyundai Xcent,2014,...,NaN,https://www.cardekho.com/buy-used-car-details/...,3995mm,1660mm,1520mm,2425mm,5 Speed,172km/hr,14,19.1 kmpl
4,0,Diesel,SUV,"60,000",Manual,1,1st Owner,Maruti,Maruti SX4 S Cross,2015,...,NaN,https://www.cardekho.com/used-car-details/used...,4300mm,1785mm,1595mm,2600mm,5 Speed,190 Kmph,16,23.65 kmpl
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1476,0,Diesel,SUV,"1,56,039",Manual,2,2nd Owner,Toyota,Toyota Fortuner,2012,...,NaN,https://www.cardekho.com/used-car-details/used...,4705mm,1840mm,1850mm,2750mm,5 Speed,176 Kmph,17,12.55 kmpl
1477,0,Petrol,Sedan,"56,000",Manual,2,2nd Owner,Maruti,Maruti SX4,2008,...,NaN,https://www.cardekho.com/used-car-details/used...,4490mm,1735mm,1570mm,2500mm,5 Speed,177 kmph,16,15 kmpl
1478,0,Petrol,Hatchback,"42,000",Manual,2,2nd Owner,Honda,Honda Brio,2014,...,NaN,https://www.cardekho.com/used-car-details/used...,3610mm,1680mm,1500mm,2345mm,5 Speed,164 Kmph,NaN,19.4 kmpl
1479,0,Diesel,Hatchback,"93,003",Manual,1,1st Owner,Hyundai,Hyundai i20,2018,...,NaN,https://www.cardekho.com/used-car-details/used...,3985mm,1734mm,1505mm,2570mm,6 Speed,180 Kmph,16,22.54 kmpl
1480,0,Petrol,Hatchback,"36,000",Automatic,2,2nd Owner,Hyundai,Hyundai Grand i10,2017,...,NaN,https://www.cardekho.com/used-car-details/used...,3765mm,1660mm,1520mm,2425mm,4 Speed,165 Kmph,14,18.9 kmpl

In [100]:
# Drop unwanted column
df.drop('it', axis=1, inplace=True)
df.drop('ft', axis=1, inplace=True)
df.drop('km', axis=1, inplace=True)
df.drop('ownerNo', axis=1, inplace=True)
df.drop('owner', axis=1, inplace=True)
df.drop('centralVariantId', axis=1, inplace=True)
df.drop('priceActual', axis=1, inplace=True)
df.drop('priceSaving', axis=1, inplace=True)
df.drop('priceFixedText', axis=1, inplace=True)
df.drop('trendingText.imgUrl', axis=1, inplace=True)
df.drop('trendingText.heading', axis=1, inplace=True)
df.drop('trendingText.desc', axis=1, inplace=True)
df.drop('Displacement', axis=1, inplace=True)
df.drop('Value Configuration', axis=1, inplace=True)
df.drop('Compression Ratio', axis=1, inplace=True)
df.drop('BoreX Stroke', axis=1, inplace=True)
df.drop('Car Links', axis=1, inplace=True)
df.drop('Engine Displacement', axis=1, inplace=True)
df.drop('Values per Cylinder', axis=1, inplace=True)
df.drop('Fuel Suppy System', axis=1, inplace=True)

In [101]:
df.to_excel('C:/Users/Surenthiran/OneDrive/Desktop/CarDekho/df2.xlsx', index=False)

print("Data saved to Excel file successfully.")

Data saved to Excel file successfully.

In [102]:
# Import necessary libraries
import pandas as pd
from io import BytesIO

# Load the Excel file (You would need to replace 'file_path' with your actual file path)
file_path = 'C:/Users/Surenthiran/OneDrive/Desktop/CarDekho/df2.xlsx'
df = pd.read_excel(file_path, engine='openpyxl')

# Function to fill or remove missing values
def fill_missing_values(dataframe):
    for column in dataframe.columns:
        if dataframe[column].dtype in ['int64', 'float64']:  # Numerical columns
            # Use mean for imputation
            dataframe[column].fillna(dataframe[column].mean(), inplace=True)
        elif dataframe[column].dtype == 'object':  # Categorical columns
            # Use mode for imputation or create a new category for missing values
            mode_value = dataframe[column].mode()[0]
            dataframe[column].fillna(mode_value, inplace=True)
    return dataframe

# Handle missing values
df_filled = fill_missing_values(df)


# Save the filled dataframe to a new Excel file
output_file_path = 'df2.xlsx'
df_filled.to_excel(output_file_path, index=False)
print(f"Processed file saved as {output_file_path}")

C:\Users\Surenthiran\AppData\Local\Temp\ipykernel_16312\1089930405.py:18: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataframe[column].fillna(mode_value, inplace=True)
C:\Users\Surenthiran\AppData\Local\Temp\ipykernel_16312\1089930405.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataframe[column].fillna(dataframe[column].mean(), inplace=True)

Processed file saved as df2.xlsx

In [103]:
# Import necessary libraries
import pandas as pd
import re
# Load the second Excel file (You need to replace 'file_path' with the actual path of your file)
file_path = 'C:/Users/Surenthiran/OneDrive/Desktop/CarDekho/df2.xlsx'
df2 = pd.read_excel(file_path, engine='openpyxl')

# Function to standardize data formats
def standardize_formats(dataframe):
    # Remove ' kms' from 'Kms Driven' and convert to integer
    if 'Kms Driven' in dataframe.columns:
        dataframe['Kms Driven'] = dataframe['Kms Driven'].str.replace(' Kms', '').str.replace(',', '').astype(int)
    
   # Remove ' Lakh', ' Crore', and handle thousands from 'price' and convert to Lakhs
    if 'price' in dataframe.columns:
    # Remove currency symbol and units like 'Lakh', 'Crore', and commas
     dataframe['price'] = dataframe['price'].str.replace('â‚¹ ', '').str.replace(' ', '').str.replace(',', '')

# #     # Convert the cleaned price column to float
#     dataframe['price'] = dataframe['price'].astype(float)

    # Lambda function to check and convert price
    dataframe['price'] = dataframe['price'].apply(lambda x: float(x.replace('Crore', '').strip()) * 10000000 
                                              if isinstance(x, str) and 'Crore' in x 
                                              else float(x.replace('Lakh', '').strip()) * 100000 
                                              if isinstance(x, str) and 'Lakh' in x 
                                              else float(x))
    

    # Convert 'Seats' to integer
    if 'Seats' in dataframe.columns:
        dataframe['Seats'] = dataframe['Seats'].str.replace(' Seats', '').astype(int)

    # Convert 'Year of Manufacture' to integer
    if 'Year of Manufacture' in dataframe.columns:
        dataframe['Year of Manufacture'] = dataframe['Year of Manufacture'].astype(int)

    # Convert 'No of Cylinder' to integer
    if 'No of Cylinder' in dataframe.columns:
        dataframe['No of Cylinder'] = dataframe['No of Cylinder'].astype(int)

    return dataframe



# Standardize data formats
df2_standardized = standardize_formats(df2)
print("Data formats standardized successfully.")

# Save the standardized dataframe to a new Excel file
output_file_path = 'df21.xlsx'
df2_standardized.to_excel(output_file_path, index=False)
print(f"Standardized file saved as {output_file_path}")

Data formats standardized successfully.
Standardized file saved as df21.xlsx

In [106]:
import pandas as pd
import os

# File paths
input_path = r"C:/Users/Surenthiran/OneDrive/Desktop/CarDekho/df21.xlsx"
output_path = os.path.join(os.path.dirname(input_path), "df21.xlsx")

# Read the Excel file
df = pd.read_excel(input_path)

# Function to add 'mm' if it's missing
def add_mm(value):
    if isinstance(value, str) and not value.endswith('mm'):
        return value + 'mm'
    elif isinstance(value, (int, float)):
        return f"{value}mm"
    return value

# Apply the function to each column
for col in ['Length', 'Width', 'Height', 'Wheel Base']:
    df[col] = df[col].apply(add_mm)

# Save the updated data
df.to_excel(output_path, index=False)

print(f"Data updated and saved to '{output_path}'")

Data updated and saved to 'C:/Users/Surenthiran/OneDrive/Desktop/CarDekho\df21.xlsx'

In [107]:
import pandas as pd
import re

# Function to extract horsepower (HP) and RPM from 'Max Power' column
def extract_hp_rpm(power_str):
    if isinstance(power_str, str):
        # Extract HP value (e.g., "118.36bhp@6000rpm" -> 118.36)
        hp_match = re.search(r'(\d+\.?\d*)bhp', power_str)
        hp = float(hp_match.group(1)) if hp_match else None

        # Extract RPM value (e.g., "118.36bhp@6000rpm" -> 6000)
        rpm_match = re.search(r'@(\d+)rpm', power_str)
        rpm = int(rpm_match.group(1)) if rpm_match else None

        return hp, rpm
    return None, None

# Function to calculate max torque
def calculate_torque(hp, rpm):
    if hp and rpm:
        return round((5252 * hp) / rpm, 2)  # Torque in lb-ft, rounded to 2 decimal places
    return None

# Load the Excel file
input_file_path = r'C:/Users/Surenthiran/OneDrive/Desktop/CarDekho/df21.xlsx'
df = pd.read_excel(input_file_path)

# Ensure that the 'Max Power' column is read as string
df['Max Power'] = df['Max Power'].astype(str)

# Apply extraction and torque calculation to each row
df['Horsepower'], df['RPM'] = zip(*df['Max Power'].map(extract_hp_rpm))
df['Max Torque (Calculated)'] = df.apply(lambda row: calculate_torque(row['Horsepower'], row['RPM']), axis=1)

# Convert the calculated torque to Nm (from lb-ft to Nm: 1 lb-ft = 1.3558 Nm)
df['Max Torque (Calculated)'] = df['Max Torque (Calculated)'].apply(lambda x: round(x * 1.3558, 2) if x else None)

# Save the updated DataFrame back to the same Excel file
output_file_path = input_file_path  # Save to the same file
with pd.ExcelWriter(output_file_path, engine='openpyxl', mode='a', if_sheet_exists='replace') as writer:
    df.to_excel(writer, index=False, sheet_name='Sheet1')

print(f"Max Torque calculated and saved in {output_file_path}")

Max Torque calculated and saved in C:/Users/Surenthiran/OneDrive/Desktop/CarDekho/df21.xlsx

In [114]:
import pandas as pd

# Load the Excel file
input_file_path = r'C:/Users/Surenthiran/OneDrive/Desktop/CarDekho/df21.xlsx'
df = pd.read_excel(input_file_path)

# Remove the 'Max Power' and 'Max Torque' columns
df.drop(columns=['Max Power', 'Max Torque','RPM','Year of Manufacture','Tyre Type'], inplace=True)

# Save the updated DataFrame back to the same Excel file
output_file_path = input_file_path  # Save to the same file
with pd.ExcelWriter(output_file_path, engine='openpyxl', mode='a', if_sheet_exists='replace') as writer:
    df.to_excel(writer, index=False, sheet_name='Sheet1')

print(f"Columns 'Max Power' and 'Max Torque' removed and saved in {output_file_path}")

KeyError: "['Max Power', 'RPM', 'Year of Manufacture'] not found in axis"

In [115]:
import pandas as pd

# Load the Excel file
input_file_path = r'C:/Users/Surenthiran/OneDrive/Desktop/CarDekho/df21.xlsx'
df = pd.read_excel(input_file_path)

# Rename specific columns using a dictionary
df.rename(columns={
    'bt': 'Body type',
    'transmission': 'Transmission type',
    'oem': 'Original Equipment Manufacturer',
    'model': 'Car model',
    'modelYear': 'Year of car manufacture',
    'variantName': 'Variant name',
    'price': 'Price of the used car',
    'Kms Driven': 'Kilometers driven',
    'Ownership': 'Ownership details',
    'Horsepower': 'Max power',
    'Max Torque (Calculated)': 'Max Torque'
}, inplace=True)

# Save the updated DataFrame back to the same Excel file
output_file_path = input_file_path  # Save to the same file
with pd.ExcelWriter(output_file_path, engine='openpyxl', mode='a', if_sheet_exists='replace') as writer:
    df.to_excel(writer, index=False, sheet_name='Sheet1')

print(f"Column names updated and saved in {output_file_path}")

Column names updated and saved in C:/Users/Surenthiran/OneDrive/Desktop/CarDekho/df21.xlsx

In [116]:
# Import necessary libraries
import pandas as pd
from io import BytesIO

# Load the Excel file (You would need to replace 'file_path' with your actual file path)
file_path = 'C:/Users/Surenthiran/OneDrive/Desktop/CarDekho/df21.xlsx'
df = pd.read_excel(file_path, engine='openpyxl')

# Function to fill or remove missing values
def fill_missing_values(dataframe):
    for column in dataframe.columns:
        if dataframe[column].dtype in ['int64', 'float64']:  # Numerical columns
            # Use mean for imputation
            dataframe[column].fillna(dataframe[column].mean(), inplace=True)
        elif dataframe[column].dtype == 'object':  # Categorical columns
            # Use mode for imputation or create a new category for missing values
            mode_value = dataframe[column].mode()[0]
            dataframe[column].fillna(mode_value, inplace=True)
    return dataframe

# Handle missing values
df_filled = fill_missing_values(df)


# Save the filled dataframe to a new Excel file
output_file_path = 'df21.xlsx'
df_filled.to_excel(output_file_path, index=False)
print(f"Processed file saved as {output_file_path}")

C:\Users\Surenthiran\AppData\Local\Temp\ipykernel_16312\880188327.py:18: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataframe[column].fillna(mode_value, inplace=True)
C:\Users\Surenthiran\AppData\Local\Temp\ipykernel_16312\880188327.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataframe[column].fillna(dataframe[column].mean(), inplace=True)

Processed file saved as df21.xlsx

In [117]:
df.isnull().sum()

Body type                          0
Transmission type                  0
Original Equipment Manufacturer    0
Car model                          0
Year of car manufacture            0
Variant name                       0
Price of the used car              0
Registration Year                  0
Insurance Validity                 0
Fuel Type                          0
Seats                              0
Kilometers driven                  0
RTO                                0
Ownership details                  0
Transmission                       0
Feature                            0
Color                              0
Engine Type                        0
No of Cylinder                     0
Turbo Charger                      0
Super Charger                      0
Seating Capacity                   0
Steering Type                      0
Tyre Type                          0
Alloy Wheel Size                   0
No Door Numbers                    0
Length                             0
Width                              0
Height                             0
Wheel Base                         0
Gear Box                           0
Top Speed                          0
Alloy Wheel Size.1                 0
Mileage                            0
Max power                          0
Max Torque                         0
dtype: int64

In [118]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1481 entries, 0 to 1480
Data columns (total 36 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Body type                        1481 non-null   object
 1   Transmission type                1481 non-null   object
 2   Original Equipment Manufacturer  1481 non-null   object
 3   Car model                        1481 non-null   object
 4   Year of car manufacture          1481 non-null   int64
 5   Variant name                     1481 non-null   object
 6   Price of the used car            1481 non-null   float64
 7   Registration Year                1481 non-null   object
 8   Insurance Validity               1481 non-null   object
 9   Fuel Type                        1481 non-null   object
 10  Seats                            1481 non-null   int64
 11  Kilometers driven                1481 non-null   int64
 12  RTO                              1481 non-null   object
 13  Ownership details                1481 non-null   object
 14  Transmission                     1481 non-null   object
 15  Feature                          1481 non-null   object
 16  Color                            1481 non-null   object
 17  Engine Type                      1481 non-null   object
 18  No of Cylinder                   1481 non-null   int64
 19  Turbo Charger                    1481 non-null   object
 20  Super Charger                    1481 non-null   object
 21  Seating Capacity                 1481 non-null   int64
 22  Steering Type                    1481 non-null   object
 23  Tyre Type                        1481 non-null   object
 24  Alloy Wheel Size                 1481 non-null   int64
 25  No Door Numbers                  1481 non-null   int64
 26  Length                           1481 non-null   object
 27  Width                            1481 non-null   object
 28  Height                           1481 non-null   object
 29  Wheel Base                       1481 non-null   object
 30  Gear Box                         1481 non-null   object
 31  Top Speed                        1481 non-null   object
 32  Alloy Wheel Size.1               1481 non-null   object
 33  Mileage                          1481 non-null   object
 34  Max power                        1481 non-null   float64
 35  Max Torque                       1481 non-null   float64
dtypes: float64(3), int64(7), object(26)
memory usage: 416.7+ KB

In [120]:
df.shape

(1481, 36)